# -*- coding: utf-8 -*-
"""attention_mechanism_student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPOBX2LRJGKkxlEtp5g2UjLixfuqpZt_

# Chapter 3 실습: 어텐션 메커니즘 구현하기

교재 Chapter 3 흐름을 따라 **Dot Product Attention → Self-Attention → Q/K/V Attention → Causal Attention → Multi-Head Attention**을 직접 구현합니다.

## 실습 목표
1. Attention score, attention weight, context vector의 차이를 이해한다.
2. 행렬곱으로 Self-Attention을 구현한다.
3. Q, K, V를 사용하는 학습 가능한 Self-Attention을 구현한다.
4. GPT 계열 모델에서 필요한 causal mask를 구현한다.
5. Multi-Head Attention의 출력 shape를 이해한다.

## 진행 방식
- 배포용 노트북은 `TODO`를 채우는 방식입니다.
- 운영진용 노트북에는 정답 코드와 검증 코드가 들어 있습니다.
- 각 파트 마지막의 검증 셀을 통과해야 다음 단계로 넘어가는 것을 추천합니다.
"""

import torch
import torch.nn as nn

torch.manual_seed(123)

inputs = torch.tensor([
    [0.43, 0.15, 0.89],
    [0.55, 0.87, 0.66],
    [0.57, 0.85, 0.64],
    [0.22, 0.58, 0.33],
    [0.77, 0.25, 0.10],
    [0.05, 0.80, 0.55],
])

tokens = ["Your", "journey", "starts", "with", "one", "step"]
print("inputs.shape:", inputs.shape)

"""## Part 1. Dot Product Attention 직접 구현하기

`journey` 토큰을 query로 두고 모든 토큰과 dot product를 계산해 attention score를 만듭니다.
"""

def get_attention_scores(inputs, query_index):
    """
    inputs: [num_tokens, embedding_dim]
    query_index: 기준이 되는 토큰 위치
    return: attn_scores [num_tokens]
    """
    query = inputs[query_index]

    attn_scores = torch.empty(inputs.shape[0])

    for i, x_i in enumerate(inputs):
        attn_scores[i] = torch.dot(x_i, query)

    return attn_scores

scores = get_attention_scores(inputs, query_index=1)
print(scores)

expected_scores = torch.tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])
assert scores.shape == torch.Size([6])
assert torch.allclose(scores, expected_scores, atol=1e-4)
print("Part 1 통과")

"""## Part 2. Attention Weight와 Context Vector 구하기

Attention score에 softmax를 적용해 attention weight를 만들고, 입력 벡터들의 가중합으로 context vector를 계산합니다.
"""

def get_context_vector(inputs, query_index):
    query = inputs[query_index]
    attn_scores = torch.empty(inputs.shape[0])
    for i, x_i in enumerate(inputs):
        attn_scores[i] = torch.dot(x_i, query)

    attn_weights = torch.softmax(attn_scores, dim=0)

    context_vec = torch.zeros(query.shape)
    for i, x_i in enumerate(inputs):
        context_vec += attn_weights[i] * x_i

    return context_vec, attn_weights

context_vec, attn_weights = get_context_vector(inputs, query_index=1)
print("attention weights:", attn_weights)
print("sum:", attn_weights.sum())
print("context vector:", context_vec)

assert attn_weights.shape == torch.Size([6])
assert torch.allclose(attn_weights.sum(), torch.tensor(1.0), atol=1e-6)
assert context_vec.shape == torch.Size([3])
expected_context = torch.tensor([0.4419, 0.6515, 0.5683])
assert torch.allclose(context_vec, expected_context, atol=1e-4)
print("Part 2 통과")

"""## Part 3. 모든 토큰에 대해 Self-Attention 계산하기

`inputs @ inputs.T`로 모든 토큰 쌍의 attention score matrix를 한 번에 계산합니다.
"""

def self_attention_basic(inputs):
    """
    trainable weight가 없는 기본 self-attention 구현
    return: attn_weights [num_tokens, num_tokens], context_vecs [num_tokens, embedding_dim]
    """
    attn_scores = inputs @ inputs.T

    attn_weights = torch.softmax(attn_scores, dim=-1)

    context_vecs = attn_weights @ inputs

    return attn_weights, context_vecs

attn_weights_basic, context_vecs_basic = self_attention_basic(inputs)
print("attn_weights_basic.shape:", attn_weights_basic.shape)
print("context_vecs_basic.shape:", context_vecs_basic.shape)
print("row sums:", attn_weights_basic.sum(dim=-1))

assert attn_weights_basic.shape == torch.Size([6, 6])
assert context_vecs_basic.shape == torch.Size([6, 3])
assert torch.allclose(attn_weights_basic.sum(dim=-1), torch.ones(6), atol=1e-6)
assert torch.allclose(context_vecs_basic[1], torch.tensor([0.4419, 0.6515, 0.5683]), atol=1e-4)
print("Part 3 통과")

"""## Part 4. Q, K, V를 사용하는 Self-Attention 구현하기

입력 벡터를 학습 가능한 가중치 행렬로 Query, Key, Value로 변환합니다. 이후 scaled dot-product attention을 계산합니다.
"""

def self_attention_qkv_manual(inputs, d_out=2):
    torch.manual_seed(123)
    d_in = inputs.shape[1]

    W_query = nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
    W_key = nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
    W_value = nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

    queries = inputs @ W_query
    keys = inputs @ W_key
    values = inputs @ W_value

    attn_scores = queries @ keys.T

    d_k = keys.shape[-1]
    attn_weights = torch.softmax(attn_scores / d_k**0.5, dim=-1)

    context_vecs = attn_weights @ values

    return context_vecs, attn_weights, queries, keys, values

context_vecs_qkv, attn_weights_qkv, queries, keys, values = self_attention_qkv_manual(inputs)
print("queries.shape:", queries.shape)
print("keys.shape:", keys.shape)
print("values.shape:", values.shape)
print("attn_weights_qkv.shape:", attn_weights_qkv.shape)
print("context_vecs_qkv.shape:", context_vecs_qkv.shape)

assert queries.shape == torch.Size([6, 2])
assert keys.shape == torch.Size([6, 2])
assert values.shape == torch.Size([6, 2])
assert attn_weights_qkv.shape == torch.Size([6, 6])
assert context_vecs_qkv.shape == torch.Size([6, 2])
assert torch.allclose(attn_weights_qkv.sum(dim=-1), torch.ones(6), atol=1e-6)
print("Part 4 통과")

"""## Part 5. `nn.Module`로 SelfAttention 클래스 만들기

`nn.Linear`를 사용해 재사용 가능한 Self-Attention 모듈을 구현합니다.
"""

class SelfAttention(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.T

        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )

        context_vecs = attn_weights @ values

        return context_vecs

torch.manual_seed(789)
sa = SelfAttention(d_in=3, d_out=2)
out_sa = sa(inputs)
print(out_sa)
print(out_sa.shape)

assert out_sa.shape == torch.Size([6, 2])
print("Part 5 통과")

"""## Part 6. Causal Mask 적용하기

GPT 계열 모델은 현재 토큰보다 미래에 있는 토큰을 보면 안 됩니다. 미래 위치를 `-inf`로 바꾼 뒤 softmax를 적용합니다.
"""

def apply_causal_mask(attn_scores):
    context_length = attn_scores.shape[0]

    mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)

    masked_scores = attn_scores.masked_fill(mask.bool(), -torch.inf)

    return masked_scores

attn_scores_qkv = queries @ keys.T
masked_scores = apply_causal_mask(attn_scores_qkv)
masked_weights = torch.softmax(masked_scores / keys.shape[-1]**0.5, dim=-1)
print(masked_weights)
print("row sums:", masked_weights.sum(dim=-1))

assert masked_weights.shape == torch.Size([6, 6])
assert torch.allclose(masked_weights.sum(dim=-1), torch.ones(6), atol=1e-6)
assert torch.all(masked_weights[0, 1:] == 0)
assert torch.all(masked_weights[1, 2:] == 0)
assert torch.all(masked_weights[2, 3:] == 0)
print("Part 6 통과")

"""## Part 7. Attention Dropout 적용하기

학습 중 일부 attention 연결을 무작위로 제거해 특정 연결에 과도하게 의존하는 것을 줄입니다.
"""

def apply_attention_dropout(attn_weights, dropout_rate=0.5):
    torch.manual_seed(123)

    dropout = nn.Dropout(dropout_rate)

    dropped_weights = dropout(attn_weights)

    return dropped_weights

for p in [0.0, 0.1, 0.5]:
    dropped = apply_attention_dropout(masked_weights, dropout_rate=p)
    print(f"dropout={p}")
    print(dropped)

assert apply_attention_dropout(masked_weights, 0.0).shape == masked_weights.shape
print("Part 7 통과")

"""## Part 8. CausalAttention 클래스 완성하기

Q/K/V, causal mask, dropout을 모두 포함한 GPT 스타일 attention 모듈입니다. 입력 shape는 `[batch_size, num_tokens, d_in]`입니다.
"""

class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

        self.dropout = nn.Dropout(dropout)

        self.register_buffer("mask", torch.triu(torch.ones(context_length, context_length), diagonal=1))

    def forward(self, x):
        b, num_tokens, d_in = x.shape

        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.transpose(1, 2)

        attn_scores.masked_fill_(self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)

        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)

        attn_weights = self.dropout(attn_weights)

        context_vecs = attn_weights @ values

        return context_vecs

batch = torch.stack((inputs, inputs), dim=0)
torch.manual_seed(123)
ca = CausalAttention(d_in=3, d_out=2, context_length=batch.shape[1], dropout=0.0)
context_vecs_ca = ca(batch)
print(context_vecs_ca)
print(context_vecs_ca.shape)

assert context_vecs_ca.shape == torch.Size([2, 6, 2])
print("Part 8 통과")

"""## Part 9. Multi-Head Attention 구현하기: Wrapper 방식

여러 개의 CausalAttention head를 병렬로 실행한 뒤 마지막 차원 기준으로 concat합니다.
"""

class MultiHeadAttentionWrapper(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        self.heads = nn.ModuleList([
            CausalAttention(d_in, d_out, context_length, dropout, qkv_bias)
            for _ in range(num_heads)
        ])

    def forward(self, x):
        return torch.cat([head(x) for head in self.heads], dim=-1)

torch.manual_seed(123)
mha_wrapper = MultiHeadAttentionWrapper(d_in=3, d_out=2, context_length=6, dropout=0.0, num_heads=2)
context_vecs_mha_wrapper = mha_wrapper(batch)
print(context_vecs_mha_wrapper)
print(context_vecs_mha_wrapper.shape)

assert context_vecs_mha_wrapper.shape == torch.Size([2, 6, 4])
print("Part 9 통과")

"""## Part 10. 효율적인 MultiHeadAttention 구현하기

Q/K/V를 한 번에 계산한 뒤 `view`, `transpose`로 head를 나눕니다. 실제 Transformer 구현에 더 가까운 방식입니다.
"""

class MultiHeadAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        assert d_out % num_heads == 0, "d_out은 num_heads로 나누어 떨어져야 합니다."
        self.d_out = d_out
        self.num_heads = num_heads
        self.head_dim = d_out // num_heads

        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

        self.out_proj = nn.Linear(d_out, d_out)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer("mask", torch.triu(torch.ones(context_length, context_length), diagonal=1))

    def forward(self, x):
        b, num_tokens, d_in = x.shape

        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        keys = keys.view(b, num_tokens, self.num_heads, self.head_dim)
        queries = queries.view(b, num_tokens, self.num_heads, self.head_dim)
        values = values.view(b, num_tokens, self.num_heads, self.head_dim)

        keys = keys.transpose(1, 2)
        queries = queries.transpose(1, 2)
        values = values.transpose(1, 2)

        attn_scores = queries @ keys.transpose(2, 3)

        mask_bool = self.mask.bool()[:num_tokens, :num_tokens]
        attn_scores.masked_fill_(mask_bool, -torch.inf)

        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)

        context_vec = (attn_weights @ values).transpose(1, 2)

        context_vec = context_vec.contiguous().view(b, num_tokens, self.d_out)

        context_vec = self.out_proj(context_vec)

        return context_vec

torch.manual_seed(123)
mha = MultiHeadAttention(d_in=3, d_out=4, context_length=6, dropout=0.0, num_heads=2)
context_vecs_mha = mha(batch)
print(context_vecs_mha)
print(context_vecs_mha.shape)

assert context_vecs_mha.shape == torch.Size([2, 6, 4])
print("Part 10 통과")

"""# 최종 과제: Tiny GPT Attention Block

아래 조건을 만족하는 GPT 스타일 attention block을 실행하세요.

## 조건
- 입력 shape: `[batch_size, context_length, d_in]`
- 출력 shape: `[batch_size, context_length, d_out]`
- causal mask 적용
- multi-head attention 사용

## 제출 체크리스트
1. 모든 검증 셀 통과
2. `dropout=0.0`, `dropout=0.1` 결과 비교
3. `num_heads=1`, `num_heads=2`, `num_heads=4` shape 비교
4. README에 Q/K/V, causal mask, multi-head attention을 자신의 말로 설명
"""

x = torch.randn(4, 8, 16)

model = MultiHeadAttention(
    d_in=16,
    d_out=16,
    context_length=8,
    dropout=0.1,
    num_heads=4
)

out = model(x)
print(out.shape)
assert out.shape == torch.Size([4, 8, 16])
print("최종 과제 기본 실행 통과")

"""dropout=0.0
소프트맥스를 통과한 어텐션 가중치를 100% 온전하게 사용합니다.
모델이 학습한 모든 문맥 정보를 손실 없이 활용하여 최종 문맥 벡터를 계산합니다. 실전 테스트나 텍스트를 생성할 때 사용하는 설정입니다.

dropout=0.1
어텐션 가중치 행렬의 원소 중 무작위로 10%를 골라 0으로 만들어 버립니다.
0이 되어버린 10%의 빈자리를 보상하기 위해, 살아남은 나머지 90%의 가중치 값들을 약 1.11배 (1 / 0.9) 키워줍니다.

이를 통해 모델은 일부 힌트가 사라져도 나머지 문맥을 골고루 활용해 정답을 유추하는 유연하고 튼튼한 신경망으로 성장합니다. (출력 텐서의 최종 Shape는 변하지 않고 내부 값만 변경됩니다.)

행렬을 쪼개는 차원이 달라짐
16이라는 전체 임베딩 차원을 4개의 헤드가 사용한다면, 각 헤드는 4차원씩 나누어 맡아 독립적으로 문맥을 분석합니다. 계산이 끝난 후 .view()를 통해 다시 하나로 합치기 때문에 최종 Shape는 항상 [4, 8, 16]으로 복구됩니다.

Q: 쿼리 내가 지금 알고 싶은 것
K; 키 대상 단어의 고유 태그
V: 벨류 각 단어의 정보
코잘 마스크 : 이전 정보로 다음 정보를 만들기 위해 미래 정보 차단
멀티 헤드 어텐션: 임베딩 차원을 여러개의 작은 헤드로 쪼개서 다양한 관점으로 단어 사이의 관계를 병렬적으로 포착
"""